In [49]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
array = np.array(range(5))

In [8]:
array

array([0, 1, 2, 3, 4])

In [9]:
array*2

array([0, 2, 4, 6, 8])

In [11]:
array.ndim

1

In [12]:
np.array([range(5)]).ndim

2

In [14]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [29]:
np.linspace(0, -1, 10)

array([ 0.        , -0.11111111, -0.22222222, -0.33333333, -0.44444444,
       -0.55555556, -0.66666667, -0.77777778, -0.88888889, -1.        ])

In [32]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

To get random numbers from a uniform distribution [0, 1)

In [54]:
np.random.rand(3,4)*10

array([[8.47910297, 8.19263094, 5.30522221, 8.22639303],
       [9.52526302, 8.36317596, 2.23524657, 1.27816   ],
       [0.62500425, 0.60868737, 9.30157441, 8.08494052]])

To get random numbers from the Gaussian distribution (mean=0, std=1)

In [53]:
np.random.randn(3,3)

array([[ 1.23613142, -0.16602236, -0.82809443],
       [ 1.01908114, -0.79503536,  1.01798558],
       [-0.4227402 , -0.20030664,  0.28555137]])

In [43]:
np.random.rand(3)

array([0.42956795, 0.36057454, 0.90974829])

In [86]:
np.random.randint(3,30, 5)

array([ 8, 28, 14, 20, 19])

In [59]:
a = np.arange(10)
a.ndim

1

In [76]:
a = a.reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [77]:
a.std()

2.8722813232690143

In [78]:
a.mean()

4.5

In [79]:
a.argmax()

9

In [80]:
a.size

10

In [81]:
a.dtype

dtype('int32')

In [83]:
a[0]

array([0, 1, 2, 3, 4])

In [84]:
arr = np.arange(0, 11)
arr[1::3]

array([ 1,  4,  7, 10])

In [85]:
arr[:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [89]:
arr_2 = arr
arr_2[:] = 30

arr

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30])

In [91]:
arr = np.arange(0, 11)

arr_2 = arr.copy()
arr_2[:] = 30

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
np.array(['*' * min(i, 2 * 5 -i) for i in range(1, 2*5)])

array(['*', '**', '***', '****', '*****', '****', '***', '**', '*'],
      dtype='<U5')

In [136]:
arr_2d = np.random.randn(3,4)
arr_2d

array([[-0.18860706,  0.87952605, -0.31104831, -1.69129652],
       [-0.22881164, -0.10254305, -2.22724306,  1.1658574 ],
       [-1.04166283, -1.00235078,  0.01299715, -0.82834624]])

In [137]:
arr_2d[:, 1]

array([ 0.87952605, -0.10254305, -1.00235078])

In [138]:
arr_2d[2, :]

array([-1.04166283, -1.00235078,  0.01299715, -0.82834624])

In [139]:
arr_2d.diagonal()

array([-0.18860706, -0.10254305,  0.01299715])

In [140]:
arr_2d[arr_2d > 0.5]

array([0.87952605, 1.1658574 ])

In [141]:
arr_2d.flatten()

array([-0.18860706,  0.87952605, -0.31104831, -1.69129652, -0.22881164,
       -0.10254305, -2.22724306,  1.1658574 , -1.04166283, -1.00235078,
        0.01299715, -0.82834624])

In [142]:
np.exp(arr_2d)

array([[0.82811184, 2.40975734, 0.73267848, 0.18428045],
       [0.79547836, 0.9025393 , 0.10782529, 3.20867282],
       [0.35286744, 0.36701565, 1.01308198, 0.43677101]])

In [143]:
np.sin(arr_2d)

array([[-0.18749084,  0.77043682, -0.30605681, -0.99274863],
       [-0.2268203 , -0.10236344, -0.79216581,  0.91912646],
       [-0.86324479, -0.84273879,  0.01299678, -0.73681428]])

In [144]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [146]:
np.arange(10,51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [147]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [148]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [154]:
np.random.rand()

0.48980792413728413

In [155]:
np.random.randn(25)

array([-0.1631641 ,  0.83781407, -1.76596434,  1.47273009, -0.2700944 ,
       -0.06285814, -0.89850109,  1.29320575,  0.45012274, -0.07261702,
       -0.71610668, -0.59313144,  0.86323792,  0.89614462, -1.26050618,
        0.4570072 , -0.89513594,  0.96541212,  0.09717838, -0.61717315,
       -1.14553817,  0.96951094,  0.77871587, -0.47165478, -0.22980312])

In [159]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [160]:
a[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [161]:
a[3, -1]

20

In [163]:
a[3:, ]

array([18, 23])

In [164]:
a.sum()

325

In [167]:
[a[:, i].sum() for i in range(5)]

[55, 60, 65, 70, 75]

In [168]:
np.arange(1, 101) / 100 re

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])